# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/django/django-blog"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/flask/fruits-rest-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/aiohttp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/bottle/different-module"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/bottle/helloworld"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/dash"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/django/django-blog"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/django/hello-world"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/falcon"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/fastapi"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/flask/fruits-rest-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/flask/helloworld"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/pyramid/pyramidsite"
    schedule:
      interval: "weekly"
